idb_path: "Dropbox/aims_db/scan_room_up_down_final_2.idb"
odb_path: "Dropbox/aims_db/scan_room_up_down.odb"
# idb_path: "Dropbox/aims_db/scan_room_final_2.idb"
# odb_path: "Dropbox/aims_db/scan_room.odb"

gravity: [0, 0, -9.79343]

time_calibrate: 0
time_start: 9.6
time_end: 72.
dt: 0.0001

features:
  min_init_confidence: 0.25
  max_missed_frames: 10
  new_keyframe_threshold: 5

# camera parameters
camera:
  fx: 432. # pixels
  fy: 432. # pixels
  cx: 317. # pixels
  cy: 252. # pixels
  pixel_noise: 0.5
  distortion: [-0.29932978711199204, 0.09469642895565503, 8.98894755601866e-05, 0.000298086422736973, 0.0]


# imu parameters
imu:
  gyro_noise: 0.001
  gyro_walk: 0.00004
  accel_noise: 0.015
  accel_walk: 0.0002

rangefinder:
  range_noise: 0.0003

# intersensor parameters
intersensor:
  p_c_i: [0.0508, -0.0508, 0.]
  p_r_i: [0.145, 0.025 , 0.044]
  q_ic: [0.5, 0.5,  0.5,  0.5]
  q_ir: [0, 0, 0, 1.]

# initial conditions
x0:
  p_i_w: [1.7787900585853405, -0.05203842134745301, 0.14761650134065427]
  v_i_w: [0.,  0.,  0.] # m/s
  q_wi: [0.9994169511398803, -0.032440564513200175, 0.010586681835438929, -0.001135655450701997]

  gyro_bias: [0.,0.,0.] # rad/s
  accel_bias: [0.,0.,0.] # m/s^2


# initial 3 sigma bounds
x0_3_sigma:
  p_i_w: 0.001 # m
  v_i_w: 0.0001 # m/s
  theta_wi: 0.001 # degrees
  gyro_bias: 0.001 # rad/s
  accel_bias: 0.001 # m/s^2
