idb_path: "Dropbox/aims_db/medium_focal.idb"
odb_path: "Dropbox/aims_db/medium_focal.odb"

gravity: [0, 0, -9.79343]

time_calibrate: 5
time_start: 10
time_end: 75.
dt: 0.005

# camera parameters
camera:
  fx: 1144. # pixels
  fy: 1147. # pixels
  cx: 317.158725 # pixels
  cy: 277.624894 # pixels
  pixel_noise: 0.3
  distortion: [0, 0, 0, 0, 0.0]

# imu parameters
imu:
  gyro_noise: 0.001
  gyro_walk: 0.00004
  accel_noise: 0.015
  accel_walk: 0.0002

rangefinder:
  range_noise: 0.001

# intersensor parameters
intersensor:
  p_c_i: [-0.05, 0., 0.]
  p_r_i: [0.13, -0.025 ,0.01]
  q_ic: [0.5, 0.5,  0.5,  0.5]
  q_ir: [0, 0, 0, 1.]

# initial conditions
x0:
  p_i_w: [ 0.131977,  0.872755,  0.557878] # m
  v_i_w: [0., 0., 0.] # m/s
  q_wi: [ 0.715077, -0.69854 , -0.019787, -0.01776 ]


  gyro_bias: [-0.012205, -0.000213, -0.006672] # rad/s
  accel_bias: [0.026356, -0.014315, -0.057953] # m/s^2


# initial 3 sigma bounds
x0_3_sigma:
  p_i_w: 0.001 # m
  v_i_w: 0.001 # m/s
  theta_ic: 1 # degrees
  gyro_bias: 0.01 # rad/s
  accel_bias: 0.01 # m/s^2
