idb_path: "Dropbox/aims_db/turn_corner_5.idb"
odb_path: "Dropbox/aims_db/turn_corner_5.odb"

gravity: [0, 0, -9.79343]

time_calibrate: 5
time_start: 4.5
time_end: 70
dt: 0.0001

# camera parameters
camera:
  fx: 429.464225  # pixels
  fy: 429.464297 # pixels
  cx: 313.398271 # pixels
  cy: 260.449116 # pixels
  pixel_noise: 0.3
  distortion: [-0.213922, 0.088003, 0.000180, -0.000312, 0.000000]

# imu parameters
imu:
  gyro_noise: 0.001
  gyro_walk: 0.00004
  accel_noise: 0.02
  accel_walk: 0.0002

rangefinder:
  range_noise: 0.001

# intersensor parameters
intersensor:
  p_c_i: [-0.05, 0., 0.]
  p_r_i: [0.13, -0.025 ,0.01]
  q_ic: [0.5, 0.5,  0.5,  0.5]
  q_ir: [0, 0, 0, 1.]

# initial conditions
x0:
  p_i_w: [ 0.649228, -1.388252,  0.110156] # m
  v_i_w: [0., 0., 0.] # m/s
  q_wi: [-0.677486,  0.73551,   0.003617,  0.004956]



  gyro_bias: [-0.012205, -0.000213, -0.006672] # rad/s
  accel_bias: [0.026356, -0.014315, -0.057953] # m/s^2


# initial 3 sigma bounds
x0_3_sigma:
  p_i_w: 0.0001 # m
  v_i_w: 0.0001 # m/s
  theta_wi: 0.005 # degrees
  gyro_bias: 0.01 # rad/s
  accel_bias: 0.01 # m/s^2
