%YAML:1.0
aruco_bc_nmarkers: 4
aruco_bc_mInfoType: 0
aruco_bc_markers:
   - { id:1, corners:[ [ -0.2765, 0.025, 0. ],
                       [ -0.025, 0.025, 0 ],
                       [ -0.025, 0.2765, 0 ],
                       [ -0.2765, 0.2765, 0 ] ] }
   - { id:50, corners:[ [ 0.025, 0.025, 0. ],
                        [ 0.2765, 0.025, 0 ],
                        [ 0.2765, 0.2765, 0 ],
                        [ 0.025, 0.2765, 0 ] ] }
   - { id:100, corners:[ [ -0.2765, -0.2765, 0. ],
                         [ -0.025, -0.2765, 0 ],
                         [ -0.025, -0.025, 0 ],
                         [ -0.2765, -0.025, 0 ] ] }
   - { id:150, corners:[ [ 0.025, -0.2765, 0. ],
                         [ 0.2765, -0.2765, 0 ],
                         [ 0.2765, -0.025, 0 ],
                         [ 0.025, -0.025, 0 ] ] }
